services:
  db:
    build: ./backend/db
    ports:
      - 2000:5432
    environment:
      - POSTGRES_DB=eada
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Password0.
    volumes:
      - ./backend/db/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "eada", "-d", "eada"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  db_client:
    build: ./backend/db/pgadmin
    depends_on:
      db:
        condition: service_started
        restart: true
    ports:
      - 2001:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=Password0.

  api_migrate:
    build: ./backend/api
    depends_on:
      db:
        condition: service_healthy
        restart: true
    command: run db:migrate

  api:
    build: ./backend/api
    depends_on:
      api_migrate:
        condition: service_completed_successfully
        restart: true
    ports:
      - 3000:3000
    develop:
      watch:
        - action: rebuild
          path: ./backend/api/package.json
        - action: sync+restart
          path: ./backend/api/src/routes
          target: /app/src/routes
        - action: sync+restart
          path: ./backend/api/src/db
          target: /app/src/db
        - action: sync+restart
          path: ./backend/api/.env.compose
          target: /app/.env

  spa:
    build: ./frontend/spa
    ports:
      - 3010:5173
    develop:
      watch:
        - action: sync
          path: ./frontend/spa/src
          target: /app/src
        - action: sync+restart
          path: ./frontend/spa/tailwind.config.js
          target: /app/tailwind.config.js
        - action: sync+restart
          path: ./frontend/spa/template.env
          target: /app/.env
